### ISSUE TITLE
dataFrame slice / sublist

### ISSUE THREAD

**Issue by knoxg** [vmzakharov/dataframe-ec#17]
Is there a simple way of getting a slice of a dataframe i.e. to return rows between two row indexes similar to List.subList(int fromIndex, int toIndex) 

I was looking at dataFrame.selectBy(filterExpression), but I don't think there's a way of referencing the current row index in the expression. 

Or rather than using a DSL to express filterExpressions, could it be possible to expose the records as a Stream that we could then filter and collect into a new DataFrame ?

**Comment by knoxg** [comment]
nvm, don't think dataframes fit my use-case anyway

**Comment by vmzakharov** [comment]
@knoxg - any chance you could describe your use case, I am just curious what it is. FWIW, each one of your original requests is pretty straightforward to implement - all the necessary bits are there (copying rows into a target data frame, the concept of a row/cursor, which is used in the `forEach()` method), it is just that there have been no requirements for it yet.
