### ISSUE TITLE
Please support Apache Arrow Frame compatibility

### ISSUE THREAD

**Issue by thesteve0** [vmzakharov/dataframe-ec#25]
Adding support for Apache Arrow would greatly increase the interoperability between application developers and data scientists. https://arrow.apache.org/

It would be much more efficient to share data structures between dataframe-ec and many of the other dataframe like frameworks. It would also allow python users to move their work to Java for the more memory intensive operations.

There is already a Java library for Arrow. 
https://arrow.apache.org/docs/java/
https://central.sonatype.com/search?q=g:org.apache.arrow%20%20v:17.0.0&smo=true

Thanks for the great work!

**Comment by vmzakharov** [comment]
Thank you for opening the issue. Will look into this. Note that it will be a separate project.

**Comment by vmzakharov** [comment]
Support for Apache Arrow is available in [this repo](https://github.com/vmzakharov/dataframe-ec-arrow-support). Note that the initial implementation is just a basic data frame converter to/from `VectorSchemaRoot`.
