### ISSUE TITLE
Feature Request: isEmpty | isNotEmpty

### ISSUE THREAD

**Issue by carslan** [vmzakharov/dataframe-ec#5]
Can we have methods that directly tell us whether the DataFrame is empty or not instead of checking the rowCount?

Thank you so much in advance.

**Comment by mehmandarov** [comment]
I can implement `isEmpty` if you are interested in this feature. As far as I can see it should be added to `DataFrame.java` with a corresponding tests in `BasicDataFrameTest.java`.

**Comment by carslan** [comment]
if you could, I would really appreciate. will we have `isNotEmpty` as well?

**Comment by mehmandarov** [comment]
@carslan: Can you please verify that this implementation works for you?

**Comment by carslan** [comment]
sincere, apologies for so late response. it works as expected. thank you so much.
